### ISSUE TITLE
在 options 中添加方位选项

### ISSUE THREAD

**Issue by SigureMo** [yanjun0501/vuepres-plugin-live2d#4]
在右下角的模型很容易遮挡返回顶端插件

如果增加选项

``` js
[
  "position": "left" // defaut: "right"
]
```

这样可能会解决上述麻烦

**Comment by yanjun0501** [comment]
收到 稍后跟一个feat

**Comment by SigureMo** [comment]
回得好快 😹 ，多谢啦~

**Comment by yanjun0501** [comment]
应该的应该的(:感谢

**Comment by yanjun0501** [comment]
fix

**Comment by yanjun0501** [comment]
FIX ON [#2cbc5aa](https://github.com/yanjun0501/vuepress-plugin-live2d/commit/f609db328e024558831001f8d6478ee1e1935bad)
